const {
  API_PORT = 3000,
  NODE_ENV,
  GITHUB_API_BASE_URL,
  PROJECT_REPOSITORIES,
  GITHUB_TOKEN,
  POSTGRES_PASSWORD,
  POSTGRES_USERNAME,
  POSTGRES_URL,
  POSTGRES_DATABASE
} = process.env;

export {
  API_PORT,
  NODE_ENV,
  GITHUB_API_BASE_URL,
  PROJECT_REPOSITORIES,
  GITHUB_TOKEN,
  POSTGRES_PASSWORD,
  POSTGRES_USERNAME,
  POSTGRES_URL,
  POSTGRES_DATABASE
};