const {
  API_PORT = 3000,
  NODE_ENV,
  GITHUB_API_BASE_URL,
  PROJECT_REPOSITORIES,
  GITHUB_TOKEN
} = process.env;

export {
  API_PORT,
  NODE_ENV,
  GITHUB_API_BASE_URL,
  PROJECT_REPOSITORIES,
  GITHUB_TOKEN
};